
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/
windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Progress Dialog — Dolphin)$
windowrule = float on, match:class ^(org.kde.dolphin)$, match:title ^(Copying — Dolphin)$
windowrule = float on, match:title ^(About Mozilla Firefox)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(firefox)$, match:title ^(Library)$
windowrule = float on, match:class ^(kitty)$, match:title ^(top)$
windowrule = float on, match:class ^(kitty)$, match:title ^(btop)$
windowrule = float on, match:class ^(kitty)$, match:title ^(htop)$
windowrule = float on, match:class ^(vlc)$
windowrule = float on, match:class ^(kvantummanager)$
windowrule = float on, match:class ^(qt5ct)$
windowrule = float on, match:class ^(qt6ct)$
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(org.kde.ark)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-applet)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$

windowrule = float on, match:class ^(Signal)$ # Signal-Gtk
windowrule = float on, match:class ^(com.github.rafostar.Clapper)$ # Clapper-Gtk
windowrule = float on, match:class ^(app.drey.Warp)$ # Warp-Gtk
windowrule = float on, match:class ^(net.davidotek.pupgui2)$ # ProtonUp-Qt
windowrule = float on, match:class ^(yad)$ # Protontricks-Gtk
windowrule = float on, match:class ^(eog)$ # Imageviewer-Gtk
windowrule = float on, match:class ^(io.github.alainm23.planify)$ # planify-Gtk
windowrule = float on, match:class ^(io.gitlab.theevilskeleton.Upscaler)$ # Upscaler-Gtk
windowrule = float on, match:class ^(com.github.unrud.VideoDownloader)$ # VideoDownloader-Gkk
windowrule = float on, match:class ^(io.gitlab.adhami3310.Impression)$ # Impression-Gtk
windowrule = float on, match:class ^(io.missioncenter.MissionCenter)$ # MissionCenter-Gtk
windowrule = float on, match:class ^(Qemu-system-i386)$ # QEMU x86
windowrule = float on, match:class ^(qemu)$ # QEMU x86

# Special workspace rules
# -> Discord
windowrule = group set, workspace special, match:class ^(discord)$
# -> Element
windowrule = group set always, workspace special, match:class ^(cinny)$
# -> Signal
windowrule = tile on, group set, workspace special, match:class ^(Signal)$
# -> Spotify
windowrule = group set, workspace special, match:class ^(Spotify)$
# -> Heynote
windowrule = group set, workspace special, match:class ^(Heynote)$

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

layerrule = blur on, ignore_alpha 0, match:namespace notifications
layerrule = blur on, ignore_alpha 0, match:namespace swaync-notification-window
layerrule = blur on, ignore_alpha 0, match:namespace swaync-control-center
layerrule = blur on, match:namespace logout_dialog