
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=eDP-1,1920x1080, 0x0, 1
# monitor=HDMI-A-1,3840x2160@30,auto,2
