lock            'pidof hyprlock || hyprlock'
before-sleep    'loginctl lock-session'
after-resume    'niri msg action power-on-monitors'


timeout 90  'brightnessctl -s set 0' resume 'brightnessctl -r'
timeout 120 'loginctl lock-session'
timeout 150 'niri msg action power-off-monitors' resume 'niri msg action power-on-monitors'
timeout 300 'acpi -a | grep off-line && systemctl suspend'