general {
    col.active_border = rgba(BCBAD2ff) rgba(896785ff) 45deg
    col.inactive_border = rgba(454549ff) rgba(675D7Cff) 45deg
}

group {
    col.border_active = rgba(454549ff) rgba(675D7Cff) 45deg
    col.border_inactive = rgba(2C292Ccc) rgba(4C3744cc) 45deg
    col.border_locked_active = rgba(504E59ff) rgba(5B566Aff) 45deg
    col.border_locked_inactive = rgba(362F34cc) rgba(41333Dcc) 45deg
}
